name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: |
       sh ./setup.sh
    - name: Libtool
      run: |
        autoreconf -i
    - name: set flag
      run: |
        ./mingw-config
    - name: Build aria2
      run: |
        make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)" check
